apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-admin-password
  namespace: argocd
spec:
  encryptedData:
    password: AgCf9czT93hWd+ss/FRzae2qHCyleby2kIctUpGww6XdbpeHcyPhNJW/ZHb7Az9Ug8CKe3zoPzbb7qvEYd4k+YWNDcSmA9eOE9b2AyyiRbML0M8cbqJ1QF6O/5narn9Kp1N50CR01/2O2MlH+P5CN+uV41W+5lCYc0B+khVzyuQTBGVlbNr4HdXpKI86fANKVrR4GMdOLeP8YcC9d//2H/DxUpmmrEKRy5yONfJH3UXqAfoXZuwA0kFxs2SJN0I+acJPFnha4Bknt+E529wApzW5LG1AMU8Mu1jHl1R2gJDeplb8Fl93BxTR7RgZjctiP4OUohXHdp+/i8Y4b5k7NFhfJyNI+jx2umleg/s/17HYdzycicQcMMhsYl8Irh1fm7tRswagRCWmzVr4jSr0nP0n9nUR880XcVosE0Yl1jyXIHDTYcAMquYrc1D3tSXqAQCnUyj3SArgts6OFiuj+LaeHWQ3BJraPjiGs+zWxlvWHi/2jxkf9Aio1D+8ZyLfYmtPgjnU0osm3MsQeeXlGwSBm+1ZE/W7oBFtto8UVw2jhwW637POEIkK7N0jAzq1Elb18iVsEt/OqmHNPdGZIUYbg5yCQ357EFYK4eeeUXA8nusX1BiByHDvyCppqBmXp3wdZAsXiS11D/DnPKee8QuUV8NxN/4QRGSwbSswKo+FBxKkZ+7fl1t4E9KmbKzbznxmnJX/roOB2RK7304Kgjz1
  template:
    metadata:
      creationTimestamp: null
      name: argocd-admin-password
      namespace: argocd
---
