apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-service-account
  namespace: aiops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aiops
  name: chaos-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines", "chaosexperiments", "chaosresults"]
  verbs: ["create", "list", "get", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-role-binding
  namespace: aiops
subjects:
- kind: ServiceAccount
  name: chaos-service-account
  namespace: aiops
roleRef:
  kind: Role
  name: chaos-role
  apiGroup: rbac.authorization.k8s.io
