apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredImagingTag
metadata:
  name: no-latest-tag-aiops
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["aiops"]
