apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    password: AgAgckAkiyDXPJTEnADrsqPO+feJB55dj1M+JwZysYAMTFZSxbL8FWlOnb+VKS43eU2j3ec1K8JqPO5hikQOgLxqCfkz79Ky0bxObW3Ry+5qF3zlJm3Ntu8fZVSCVHMHQunmJeqx0umCVGQPKe5CsowRcFce07tW9hJC0nKotdw2OvxiD3vl6xUTMexBSzjWf1pd6qRM0fmBFAfnuq/w/wdDLMWZR4X6N//wyyzN1CZVmUsfklv7QjJprMIqCjBZ34WfaeWsd1FuoXPHpLj9ZDyAlB9Rwdv/UBjpwGl1B8YisRQmQA7SUkK24CuTn+7QJROHlPtH9FN6i5PoRrPWz40fwcA/Z2ushJb3B2kIUdXK4wfDUH7wze492RD7WPKrH1ld1rEqqsmMSLansi39PrqoG8uOEmIg8xZlSy/0t8MlDEOhYfunDzpSsWrYY/U1sOuebEjFPsRCozjinIhgOP/JJlXunY6ulsQqy7AxbD7cvCz8qAmkoovbSLX8iyEmK1xs2npuotYuQLU92BTSdeivmU/iMuwKbqHuzkw0klWQ+AzJpwrVdnlgjgZWFmPzDrRah+mZQrKVU95lZSQENbMQJ73v+IB+70f2IpK8KURlJlDv5OIn6kdFCtaRGqhmFkXHWFMhKfzjaaogkR7cGwHiOQ0B/vTLLUrY4FdooJnN9ppoOSV0oR9UHFJCtQz31S7CQkBVkQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-password
      namespace: monitoring
---
