apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-latest
  name: test-latest
  namespace: aiops
spec:
  containers:
  - image: nginx:latest
    name: test-latest
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
