apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-violation
  name: test-violation
  namespace: aiops
spec:
  containers:
  - image: nginx
    name: test-violation
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
